package com.beyondeye.k2dart

import com.pinterest.ktlint.ruleset.k2dart.rules.DataClassesRule
import org.assertj.core.api.Assertions
import org.junit.jupiter.api.Test
// *DARIO* this for collecting result of a lint of operation

class DataClassesRuleTest {
    @Test
    fun `generate stubs for data classes autogenerated methods`() {
        val code =
            """
            class SomeClass

            data class A(val a:Int, val b:String, var c:SomeClass)
            {
                fun someMethod() { print("Hi") }
            }
            """.trimIndent()
        val formattedCode =
            """
            class SomeClass

            /* data */ class A(val a:Int, val b:String, var c:SomeClass)
            {
                fun someMethod() { print("Hi") }
            }
            """.trimIndent()
        val actualFormattedCode = runRulesOnCodeFragment(code, listOf(DataClassesRule()))
        Assertions.assertThat(actualFormattedCode).isEqualTo(formattedCode)
    }


}
