/* data */ class B/* (val lst:List<A> = listOf()) */ {
final List<A> lst = listOf();

B(this.lst,);

B copyWith({
   List<A>? lst,
}) {
  return B(
    lst: lst ?? this.lst,
  );
}

// AUTOGENERATED METHOD
//TODO for maps substitute <field>==other.<field> with mapEquals(<field>,other.<field>
//TODO for lists substitute <field>==other.<field> with listEquals(<field>,other.<field>
@override
bool operator ==(Object other) =>
     identical(this, other) ||
     other is B &&
     runtimeType == other.runtimeType &&
     lst == other.lst;

@override
int get hashCode => lst.hashCode;
}
